"""Add Child model and child_disabilities join table

Revision ID: 4a64edf9ed42
Revises: 6a2f42b4d83c
Create Date: 2026-04-24 12:33:34.331367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a64edf9ed42'
down_revision = '6a2f42b4d83c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('child',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('child_disabilities',
    sa.Column('child_id', sa.Integer(), nullable=False),
    sa.Column('disability_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['child_id'], ['child.id'], ),
    sa.ForeignKeyConstraint(['disability_id'], ['disability_category.id'], ),
    sa.PrimaryKeyConstraint('child_id', 'disability_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('child_age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('child_age', sa.INTEGER(), nullable=True))

    op.drop_table('child_disabilities')
    op.drop_table('child')
    # ### end Alembic commands ###
