"""Add disability subcategories and update child relationships

Revision ID: 9bff722ff663
Revises: 66f5c3540ca6
Create Date: 2026-05-02 07:56:49.615736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bff722ff663'
down_revision = '66f5c3540ca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disability_subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['disability_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('child_disabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disability_subcategory_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'disability_subcategory', ['disability_subcategory_id'], ['id'])
        batch_op.drop_column('disability_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('child_disabilities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disability_id', sa.INTEGER(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'disability_category', ['disability_id'], ['id'])
        batch_op.drop_column('disability_subcategory_id')

    op.drop_table('disability_subcategory')
    # ### end Alembic commands ###
