"""Add support_group and group_message models

Revision ID: f336777097fc
Revises: 4a64edf9ed42
Create Date: 2026-04-27 08:54:10.959638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f336777097fc'
down_revision = '4a64edf9ed42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disability_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['disability_id'], ['disability_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_members',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['support_group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'group_id')
    )
    op.create_table('group_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['support_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_disabilities')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_disabilities',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('disability_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['disability_id'], ['disability_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'disability_id')
    )
    op.drop_table('group_message')
    op.drop_table('group_members')
    op.drop_table('support_group')
    # ### end Alembic commands ###
